### ISSUE TITLE
flexible-defaults-0.0.1.2 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [mokus0/flexible-defaults#5]
~~~
[   91s] [2 of 3] Compiling Language.Haskell.TH.FlexibleDefaults.DSL ( src/Language/Haskell/TH/FlexibleDefaults/DSL.hs, dist/build/Language/Haskell/TH/FlexibleDefaults/DSL.o )
[   91s] 
[   91s] src/Language/Haskell/TH/FlexibleDefaults/DSL.hs:24:10: error:
[   91s]     • No instance for (Semigroup (Impls s))
[   91s]         arising from the superclasses of an instance declaration
[   91s]     • In the instance declaration for ‘Monoid (Impls s)’
[   91s]    |
[   91s] 24 | instance Monoid (Impls s) where
[   91s]    |          ^^^^^^^^^^^^^^^^
~~~

Details about this issue are at https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid.

**Comment by retnuh** [comment]
Also on GHC 8.4.2:

```
Building library for flexible-defaults-0.0.1.2..
[1 of 3] Compiling Language.Haskell.TH.FlexibleDefaults.Solve ( src/Language/Haskell/TH/FlexibleDefaults/Solve.hs, dist/build/Language/Haskell/TH/FlexibleDefaults/Solve.o )

src/Language/Haskell/TH/FlexibleDefaults/Solve.hs:13:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
13 | import Data.Monoid 
   | ^^^^^^^^^^^^^^^^^^
[2 of 3] Compiling Language.Haskell.TH.FlexibleDefaults.DSL ( src/Language/Haskell/TH/FlexibleDefaults/DSL.hs, dist/build/Language/Haskell/TH/FlexibleDefaults/DSL.o )

src/Language/Haskell/TH/FlexibleDefaults/DSL.hs:24:10: error:
    • No instance for (Semigroup (Impls s))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Impls s)’
   |
24 | instance Monoid (Impls s) where
   |          ^^^^^^^^^^^^^^^^
```
