### PR TITLE
add Semigroup instance of Impls (for ghc-8.4.1, fixes #5)

### LINKED ISSUE #5: flexible-defaults-0.0.1.2 does not compile with GHC 8.4.1
~~~
[   91s] [2 of 3] Compiling Language.Haskell.TH.FlexibleDefaults.DSL ( src/Language/Haskell/TH/FlexibleDefaults/DSL.hs, dist/build/Language/Haskell/TH/FlexibleDefaults/DSL.o )
[   91s] 
[   91s] src/Language/Haskell/TH/FlexibleDefaults/DSL.hs:24:10: error:
[   91s]     • No instance for (Semigroup (Impls s))
[   91s]         arising from the superclasses of an instance declaration
[   91s]     • In the instance declaration for ‘Monoid (Impls s)’
[   91s]    |
[   91s] 24 | instance Monoid (Impls s) where
[   91s]    |          ^^^^^^^^^^^^^^^^
~~~

Details about this issue are at https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid.

### PR DESCRIPTION
**Pull request by int-e**
Note, I've opted for adding a semigroups package dependency; an alternative would be using CPP to make the instance conditional.

### CODE REVIEW

**Comment by bgamari** [comment]
It would be great if this could be merged.

**Comment by int-e** [comment]
Ping?
